<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Hora estándar de Argentina">
<General productName="Micro Focus UFT One" productVer="2021" os="" host="DESKTOP-CG560G2"><DocLocation><![CDATA[C:\Users\ezequ\Documents\UFT One\Garmin]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[Garmin]]></DName>
<Res><![CDATA[Res11]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:44]]></Time>
<TimeTick>1644589844</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://google.com.ar]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:44]]></Time>
<TimeTick>1644589844</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:44]]></Time>
<TimeTick>1644589844</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Action1]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Google]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[GPS Running Watches |]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[GPS Running Watches |.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="1" >
<Disp><![CDATA[GPS Running Watches |.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Action1" SourceLine="1" >
<Disp><![CDATA[GPS Running Watches |]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Google.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://www.garmin.com/en-US<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="19" Source="Action1" SourceLine="2" >
<Disp><![CDATA[Google.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Garmin International |]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Running.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:45]]></Time>
<TimeTick>1644589845</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Running.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="21" Source="Action1" SourceLine="3" >
<Disp><![CDATA[Garmin International |]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[GPS Running Watches |]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:46]]></Time>
<TimeTick>1644589846</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[COMPARE.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:46]]></Time>
<TimeTick>1644589846</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="Action1" SourceLine="4" >
<Disp><![CDATA[COMPARE.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Add to comparison.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:46]]></Time>
<TimeTick>1644589846</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="Action1" SourceLine="5" >
<Disp><![CDATA[Add to comparison.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Add to comparison.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:46]]></Time>
<TimeTick>1644589846</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" Source="Action1" SourceLine="6" >
<Disp><![CDATA[Add to comparison.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Add to comparison.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:46]]></Time>
<TimeTick>1644589846</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="Action1" SourceLine="7" >
<Disp><![CDATA[Add to comparison.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Add to comparison.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:47]]></Time>
<TimeTick>1644589847</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="Action1" SourceLine="8" >
<Disp><![CDATA[Add to comparison.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[COMPARE.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:47]]></Time>
<TimeTick>1644589847</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" Source="Action1" SourceLine="9" >
<Disp><![CDATA[COMPARE.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" Source="Action1" SourceLine="4" >
<Disp><![CDATA[GPS Running Watches |]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Garmin | Compare]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:48]]></Time>
<TimeTick>1644589848</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Lens Material.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:48]]></Time>
<TimeTick>1644589848</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" Source="Action1" SourceLine="12" >
<Disp><![CDATA[Lens Material.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:49]]></Time>
<TimeTick>1644589849</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:49]]></Time>
<TimeTick>1644589849</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:49]]></Time>
<TimeTick>1644589849</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:49]]></Time>
<TimeTick>1644589849</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:50]]></Time>
<TimeTick>1644589850</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="60" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="64" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="68" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="70" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="78" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="80" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:51]]></Time>
<TimeTick>1644589851</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="84" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="94" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="98" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="102" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="104" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:52]]></Time>
<TimeTick>1644589852</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="108" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="110" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="112" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="114" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="116" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="118" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="120" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="122" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="124" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="126" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:53]]></Time>
<TimeTick>1644589853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="128" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:54]]></Time>
<TimeTick>1644589854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="130" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:54]]></Time>
<TimeTick>1644589854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="132" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:54]]></Time>
<TimeTick>1644589854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="134" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:54]]></Time>
<TimeTick>1644589854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="136" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Lens Material.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/2/2022 - 11:30:54]]></Time>
<TimeTick>1644589854</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="138" Source="Action1" SourceLine="16" >
<Disp><![CDATA[Lens Material.GetCellData]]></Disp>
</NodeArgs>